-- MySQL Script generated by MySQL Workbench
-- Sat Nov 11 19:39:10 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sale
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `sale` ;

-- -----------------------------------------------------
-- Schema sale
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sale` DEFAULT CHARACTER SET utf8 ;
USE `sale` ;

-- -----------------------------------------------------
-- Table `sale`.`payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sale`.`payment` ;

CREATE TABLE IF NOT EXISTS `sale`.`payment` (
  `transaction_id` INT NOT NULL,
  `price` FLOAT NULL,
  `discount` FLOAT NULL,
  `product_price` FLOAT NULL,
  `product` VARCHAR(45) NULL,
  `payment_type` VARCHAR(45) NULL,
  `payment_date` DATETIME NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sale`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sale`.`product` ;

CREATE TABLE IF NOT EXISTS `sale`.`product` (
  `product` VARCHAR(45) NOT NULL,
  `price` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`product`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
